backend/tripify/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name='index'),
    path("about/", views.about, name='about'),
    path("book/", views.book, name='book'),
    path("package/", views.package, name='package'),
    path("vacation/", views.vacation, name='vacation'),
    path("cities/", views.cities, name='cities'),
    path("city/", views.city, name='city'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('reservations/', views.reservations, name='reservations'),
]

backend/tripify/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Continent(models.Model):
    name = models.CharField(max_length=100)
    image = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField(max_length=100)
    continent = models.ForeignKey(Continent, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='tripify/static/')

    def __str__(self):
        return self.name

class Tipovi_smestaja(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

class Tip_sobe(models.Model):
    name = models.CharField(max_length=20)
    broj_ljudi = models.IntegerField()

    def __str__(self):
        return self.name
    
class Tip_prevoza(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Smestaj(models.Model):
    name = models.CharField(max_length=100)
    kategorija = models.IntegerField(
        default=1,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
    )
    internet = models.BooleanField()
    tv = models.BooleanField()
    klima = models.BooleanField()
    sobni_frizider = models.BooleanField()
    cena_prevoza = models.IntegerField(
        validators=[
            MaxValueValidator(3000),
            MinValueValidator(100)
        ]
    )
    grad = models.ForeignKey(City, on_delete=models.CASCADE)
    tip_smestaja = models.ForeignKey(Tipovi_smestaja, on_delete=models.CASCADE)
    tip_sobe = models.ForeignKey(Tip_sobe, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Smestaj_slika(models.Model):
    img = models.ImageField(upload_to='tripify/static')
    smestaj = models.ForeignKey(Smestaj, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.smestaj.name} - {self.img.url}"
    

class Aranzman(models.Model):
    naziv = models.CharField(max_length=255, unique=True)
    opis = models.CharField(max_length=512)
    prevoz = models.ForeignKey(Tip_prevoza, on_delete=models.CASCADE)
    smestaj = models.ForeignKey(Tipovi_smestaja, on_delete=models.CASCADE)
    cena = models.IntegerField(
        validators=[
            MaxValueValidator(3000),
            MinValueValidator(500)
        ]
    )
    polazak = models.DateTimeField()
    duzina = models.IntegerField( # duzina u danima
        validators=[ # 1 do 2 nedelje
            MaxValueValidator(14),
            MinValueValidator(7)
        ]
    )
    rezervisan = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.naziv

class Termin(models.Model):
    aranzman = models.ForeignKey(Aranzman, on_delete=models.CASCADE)
    smestaj = models.ForeignKey(Smestaj, on_delete=models.CASCADE)
    vreme_stizanja = models.DateTimeField()

    def __str__(self):
        return f"{self.aranzman.naziv} - {self.smestaj.name}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    def __str__(self):
        return self.user.username
    

class Rezervacija(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    aranzman = models.ForeignKey(Aranzman, on_delete=models.CASCADE)
    broj_odraslih = models.IntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
    )
    broj_dece = models.IntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
    )
    NACINI_PLACANJA = [
        (0, 'card'),
        (1, 'cash')
    ]
    nacin_placanja = models.IntegerField(
        choices=NACINI_PLACANJA
    )
    komentar = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.user.user.first_name} - {self.aranzman.naziv}"
    

backend/tripify/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    email = forms.EmailField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = forms.CharField(validators=[phone_regex])

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'phone_number']

class BookForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)
    PAYMENT_METHODS = [(0, 'card'), (1, 'cash')]
    payment_method = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_METHODS)
    number_of_adults = forms.IntegerField(max_value=5, min_value=1)
    number_of_children = forms.IntegerField(max_value=5, min_value=1)

backend/tripify/views.py
from django.shortcuts import render, redirect
from .models import Continent, Country, City, Aranzman, Termin, Smestaj, Smestaj_slika, Tip_prevoza, Profile, Rezervacija
from datetime import datetime
from django.http import (HttpResponseBadRequest)
from django.core.paginator import Paginator
import time
from django.db.models import Sum, Q, F, OuterRef, Min, Subquery
from .forms import RegisterForm, BookForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm

def index(request):

    kontinenti = Continent.objects.all()
    gradovi = City.objects.all()

    aranzmani = Aranzman.objects.filter(polazak__gt=datetime.today()).order_by('polazak')[:3]

    aranzmani_list = []

    for aranzman in aranzmani:

        l = []

        l.append(aranzman)

        termin = Termin.objects.filter(
            aranzman=aranzman
        ).order_by('vreme_stizanja')[0]
        
        cena = aranzman.cena

        termini = Termin.objects.filter(aranzman=aranzman)

        for t in termini:
            cena += t.smestaj.cena_prevoza

        l.append(termin)
        l.append(cena)

        aranzmani_list.append(l)

    print(aranzmani_list)

    return render(request, 'home.html', { 'kontinenti': kontinenti, 'gradovi': gradovi, 'aranzmani': aranzmani_list })

def about(request):
    return render(request, 'about.html')

def book(request):

    if not request.user.is_authenticated:
        return redirect('register')
    
    id = None

    try:
        id = request.GET["id"]
        aranzman = Aranzman.objects.get(pk=id)
        if aranzman.rezervisan:
            return redirect('/')
    except:
        return HttpResponseBadRequest("ID missing/unknown")

    if request.method == 'POST':

        form = BookForm(request.POST)

        if form.is_valid():
            comment = form.cleaned_data.get('comment')
            payment_method = form.cleaned_data.get('payment_method')
            number_of_adults = form.cleaned_data.get('number_of_adults')
            number_of_children = form.cleaned_data.get('number_of_children')

            profile = Profile.objects.get(user=request.user)

            Rezervacija.objects.create(aranzman=aranzman, user=profile, broj_odraslih=number_of_adults, broj_dece=number_of_children, nacin_placanja=payment_method, komentar=comment)

            aranzman.rezervisan = True
            aranzman.save()

            return redirect('/reservations/')

    form = BookForm()

    return render(request, 'book.html', { 'aranzman': aranzman, 'form': form })

def package(request):

    kontinenti = Continent.objects.all()
    transporti = Tip_prevoza.objects.all()

    aranzmani = Aranzman.objects.filter(rezervisan=False)

    start_time = time.time()

    page = 1
    num_per_page = 50

    if "name" in request.GET and request.GET["name"] != "":
        aranzmani = aranzmani.filter(naziv__icontains=request.GET["name"])
    
    # if "continent" in request.GET and request.GET["continent"] != "":
    
    if "transport" in request.GET and request.GET["transport"] != "":
        aranzmani = aranzmani.filter(prevoz__id=request.GET["transport"])

    if "arrival" in request.GET and request.GET["arrival"] != "":
        aranzmani = aranzmani.filter(
            polazak__date=datetime.strptime(request.GET["arrival"], '%Y-%m-%d')
        )

    if "arrival" in request.GET and request.GET["arrival"] != "":
        datum_polaska = datetime.strptime(request.GET["arrival"], '%Y-%m-%d')
        aranzmani = aranzmani.filter(
            polazak__date=datum_polaska
        )
    
        if "leaving" in request.GET and request.GET["leaving"] != "":
            datum_odlaska = datetime.strptime(request.GET["leaving"], '%Y-%m-%d')
            broj_dana = (datum_odlaska - datum_polaska).days
            print(f"Broj dana: {broj_dana}")
            aranzmani = aranzmani.filter(
                duzina=broj_dana
            )
    

    aranzmani = aranzmani.annotate(cena_prevoza=Sum('termin__smestaj__cena_prevoza'))

    # aranzmani = aranzmani.annotate(ime_grada=F('termin__smestaj__grad__name'))
    
    first_term = Termin.objects.filter(aranzman=OuterRef('pk')).order_by('vreme_stizanja').values('smestaj__grad__name', 'smestaj__grad__image', 'smestaj__grad__country__continent__id')[:1]


    aranzmani = aranzmani.annotate(
        ime_grada=Subquery(first_term.values('smestaj__grad__name'))
    )

    aranzmani = aranzmani.annotate(
        slika_grada=Subquery(first_term.values('smestaj__grad__image'))
    )

    aranzmani = aranzmani.annotate(
        continent_id=Subquery(first_term.values('smestaj__grad__country__continent__id'))
    )

    if "continent" in request.GET and request.GET["continent"] != "":
        aranzmani = aranzmani.filter(continent_id=int(request.GET["continent"]))

    novi_aranzmani = list(
        aranzmani.filter(polazak__gt=datetime.now()).order_by('polazak')
    )

    novi_aranzmani.extend(
        list(
            aranzmani.filter(polazak__lt=datetime.now()).order_by('-polazak')
        )
    )

    print(len(novi_aranzmani))

    print(f"Pretraga izvrsena za: {time.time() - start_time}s")


    if "page" in request.GET:
        page = int(request.GET["page"])

    if "show" in request.GET:
        num_per_page = int(request.GET["show"])

    p = Paginator(novi_aranzmani, num_per_page)

    return render(request, 'package.html', { 'kontinenti': kontinenti, 'transporti': transporti, 'aranzmani': p.page(page) })

def vacation(request):

    id = None
    aranzman = None

    try:
        id = request.GET["id"]
        aranzman = Aranzman.objects.get(pk=id)
    except:
        return HttpResponseBadRequest("ID missing/unknown")
    
    termini = Termin.objects.filter(aranzman=aranzman)

    cena = aranzman.cena
    smestaji = []

    for termin in termini:
        cena += termin.smestaj.cena_prevoza
        smestaji.append(termin.smestaj)

    
    slike_smestaja = Smestaj_slika.objects.filter(smestaj__in=smestaji)

    return render(request, 'vacation.html', { 'aranzman': aranzman, 'termini': termini, 'cena': cena, 'slike_smestaja': slike_smestaja })

def cities(request):

    id = None
    gradovi = None
    
    try:
        id = request.GET["id"]
        kontinent = Continent.objects.get(pk=id)
        drzave = list(Country.objects.filter(continent=kontinent))
        gradovi = City.objects.filter(country__in=drzave)
    except:
        return HttpResponseBadRequest("ID missing/unknown")
    
    return render(request, 'cities.html', { 'gradovi': gradovi })

def city(request):

    id = None
    grad = None
    page = 1

    aranzmani = []
    aranzmani_list = []

    try:
        id = request.GET["id"]
        
        if "page" in request.GET:
            page = request.GET["page"]

        grad = City.objects.get(pk=id)
        smestaji = list(Smestaj.objects.filter(grad=grad))
        termini = list(Termin.objects.filter(smestaj__in=smestaji, vreme_stizanja__gt=datetime.today()).order_by('vreme_stizanja'))
        termini.extend(list(Termin.objects.filter(smestaj__in=smestaji, vreme_stizanja__lt=datetime.today()).order_by('-vreme_stizanja')))
        for termin in termini:
            if not termin.aranzman in aranzmani:
                if not termin.aranzman.rezervisan:
                    aranzmani.append(termin.aranzman)
    except:
        return HttpResponseBadRequest("ID missing/unknown")

    for aranzman in aranzmani:

        l = []

        l.append(aranzman)

        termin = Termin.objects.filter(
            aranzman=aranzman
        ).order_by('vreme_stizanja')[0]
        
        cena = aranzman.cena

        termini = Termin.objects.filter(aranzman=aranzman)

        for t in termini:
            cena += t.smestaj.cena_prevoza

        l.append(termin)
        l.append(cena)

        aranzmani_list.append(l)

    p = Paginator(aranzmani_list, 50)

    return render(request, 'city.html', { 'grad': grad, 'aranzmani': p.page(page), 'id': id })

def register_view(request):
    if request.user.is_authenticated:
        redirect('index')

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save()
            # first_name = form.cleaned_data.get('first_name')
            # last_name = form.cleaned_data.get('last_name')
            # email = form.cleaned_data.get('email')
            phone_number = form.cleaned_data.get('phone_number')
            print(phone_number)
            Profile.objects.create(user=user, phone_number=phone_number)
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            print("Uspesna registracija")
            return redirect('index')
    else:
        form = RegisterForm()
    
    return render(request, 'register.html', { 'form': form })

def login_view(request):
    
    if request.user.is_authenticated:
        logout(request)
    
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            print('valid form')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                print(f"{user.username} logged in")
                return redirect('index')
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', { 'form': form })

def reservations(request):
    
    if not request.user.is_authenticated:
        return redirect('/')

    if "cancel" in request.GET and "id" in request.GET:
        try:
            reservation = Rezervacija.objects.get(pk=request.GET["id"])
            aranzman = reservation.aranzman
            aranzman.rezervisan = False

backend/tripify/templates/__base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Tripify website" />
    <meta name="keywords" content="trip, tourist" />
    <title>Tripify</title>
    <!-- swiper css link  -->
    <link rel="stylesheet"
          href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!-- font awesome cdn link  -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <link rel="stylesheet" href="{% static 'css/about.css' %}" />
    <link rel="stylesheet" href="{% static 'css/book.css' %}" />
    <link rel="stylesheet" href="{% static 'css/package.css' %}" />
    <link rel="stylesheet" href="{% static 'css/vacation.css' %}" />
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
  </head>
  <body>
    <section class="header">
      <a href="{% url 'index' %}" class="logo">Tripify</a>
      <nav class="navbar">
        <a href="{% url 'index' %}">home</a>
        <a href="{% url 'about' %}">about</a>
        <a href="{% url 'package' %}">packages</a>
        {% if user.is_authenticated %}
        <a href="{% url 'reservations' %}">Your reservations</a>
        <a href="{% url 'login' %}">Log out</a>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'register' %}">Register</a>
        {% endif %}
        <a href="{% url 'package' %}" class="fas fa-search"></a>
      </nav>
      <form action="" class="search-bar-container">
        <input type="search" id="search-bar" placeholder="search here..." />
        <label for="search-bar" class="fas fa-search"></label>
      </form>
      <div id="menu-btn" class="fas fa-bars"></div>
    </section>
    {% block content %}
    {% endblock content %}

    <section class="footer">
      <div class="box-container">
        <div class="box">
          <h3>quick links</h3>
          <a href="{% url 'index' %}"> <i class="fas fa-angle-right"></i> home</a>
          <a href="{% url 'about' %}"> <i class="fas fa-angle-right"></i> about</a>
          <a href="{% url 'package' %}"> <i class="fas fa-angle-right"></i> package</a>
          <a href="{% url 'book' %}"> <i class="fas fa-angle-right"></i> book</a>
        </div>

        <div class="box">
          <h3>extra links</h3>
          <a href="#"> <i class="fas fa-angle-right"></i> ask questions</a>
          <a href="#"> <i class="fas fa-angle-right"></i> about us</a>
          <a href="#"> <i class="fas fa-angle-right"></i> privacy policy</a>
          <a href="#"> <i class="fas fa-angle-right"></i> terms of use</a>
        </div>

        <div class="box">
          <h3>contact info</h3>
          <a href="#"> <i class="fas fa-phone"></i> +123-456-7890 </a>
          <a href="#"> <i class="fas fa-phone"></i> +111-222-3333 </a>
          <a href="#"> <i class="fas fa-envelope"></i> tripify@gmail.com </a>
          <a href="#">
            <i class="fas fa-map"></i> Kragujevac, Serbia - 34000
          </a>
        </div>

        <div class="box">
          <h3>follow us</h3>
          <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
          <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
          <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
          <a href="#"> <i class="fab fa-linkedin"></i> linkedin </a>
        </div>
      </div>

      <div class="credit">
        created by <span>Tripify team</span> | all rights reserved!
      </div>
    </section>

    <!-- footer section ends -->

    <!-- swiper js link  -->
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

    <!-- custom js file link  -->
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

backend/tripify/templates/about.html
{% extends "__base.html" %}
{% load static %}
{% block content %}
  <div class="heading"
       style="background: url({% static 'images/header-bg-1.png' %}) no-repeat">
    <h1>about us</h1>
  </div>
  <!-- about section starts  -->
  <section class="about">
    <div class="image">
      <img src="{% static 'images/about-img.jpg' %}" alt="" />
    </div>
    <div class="content">
      <h3>why choose us?</h3>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iure numquam
        nulla iusto corporis dolor commodi libero, vitae obcaecati optio rerum
        ab culpa nesciunt, earum mollitia quasi ipsam non. Aliquid, iure.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid
        rerum, delectus voluptate aliquam quaerat iusto repellendus error
        nulla ab atque.
      </p>
      <div class="icons-container">
        <div class="icons">
          <i class="fas fa-map"></i>
          <span>top destinations</span>
        </div>
        <div class="icons">
          <i class="fas fa-hand-holding-usd"></i>
          <span>affordable price</span>
        </div>
        <div class="icons">
          <i class="fas fa-headset"></i>
          <span>24/7 guide service</span>
        </div>
      </div>
    </div>
  </section>
  <!-- about section ends -->
  <!-- reviews section starts  -->
  <section class="reviews">
    <h1 class="heading-title">clients reviews</h1>
    <div class="swiper reviews-slider">
      <div class="swiper-wrapper">
        <div class="swiper-slide slide">
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </div>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus
            facilis laudantium magnam saepe magni ullam possimus laborum
            voluptas, veniam ipsum officiis quae doloribus minima ut quis.
            Molestiae qui distinctio possimus?
          </p>
          <h3>john deo</h3>
          <span>traveler</span>
          <img src="{% static 'images/pic-1.png' %}" alt="" />
        </div>
        <div class="swiper-slide slide">
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </div>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Accusamus repellendus et suscipit optio similique totam aut
            laborum ullam sequi! In!
          </p>
          <h3>john deo</h3>
          <span>traveler</span>
          <img src="{% static 'images/pic-2.png' %}" alt="" />
        </div>
        <div class="swiper-slide slide">
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </div>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            Voluptatibus enim deserunt, ab at ea iste odio placeat doloribus
            eum dolores tempore obcaecati, dolore esse aperiam. Excepturi ad
            quo distinctio, dignissimos voluptate, dolores, saepe animi eum
            atque sint esse ab exercitationem!
          </p>
          <h3>john deo</h3>
          <span>traveler</span>
          <img src="{% static 'images/pic-3.png' %}" alt="" />
        </div>
        <div class="swiper-slide slide">
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </div>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Possimus
            recusandae cum quibusdam odio dignissimos nemo?
          </p>
          <h3>john deo</h3>
          <span>traveler</span>
          <img src="{% static 'images/pic-4.png' %}" alt="" />
        </div>
        <div class="swiper-slide slide">
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </div>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus
            facilis laudantium magnam saepe magni ullam possimus laborum
            voluptas, veniam ipsum officiis quae doloribus minima ut quis.
            Molestiae qui distinctio possimus?
          </p>
          <h3>john deo</h3>
          <span>traveler</span>
          <img src="{% static 'images/pic-5.png' %}" alt="" />
        </div>
        <div class="swiper-slide slide">
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </div>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus
            facilis laudantium magnam saepe magni ullam possimus laborum
            voluptas, veniam ipsum officiis quae doloribus minima ut quis.
            Molestiae qui distinctio possimus?
          </p>
          <h3>john deo</h3>
          <span>traveler</span>
          <img src="{% static 'images/pic-6.png' %}" alt="" />
        </div>
      </div>
    </div>
  </section>
  <!-- reviews section ends -->
  <!-- footer section starts  -->
  <section class="footer">
    <div class="box-container">
      <div class="box">
        <h3>quick links</h3>
        <a href="{% url 'index' %}"> <i class="fas fa-angle-right"></i> home</a>
        <a href="{% url 'about' %}"> <i class="fas fa-angle-right"></i> about</a>
        <a href="{% url 'package' %}"> <i class="fas fa-angle-right"></i> package</a>
        <a href="{% url 'book' %}"> <i class="fas fa-angle-right"></i> book</a>
      </div>
      <div class="box">
        <h3>extra links</h3>
        <a href="#"> <i class="fas fa-angle-right"></i> ask questions</a>
        <a href="#"> <i class="fas fa-angle-right"></i> about us</a>
        <a href="#"> <i class="fas fa-angle-right"></i> privacy policy</a>
        <a href="#"> <i class="fas fa-angle-right"></i> terms of use</a>
      </div>
      <div class="box">
        <h3>contact info</h3>
        <a href="#"> <i class="fas fa-phone"></i> +123-456-7890 </a>
        <a href="#"> <i class="fas fa-phone"></i> +111-222-3333 </a>
        <a href="#"> <i class="fas fa-envelope"></i> tripify@gmail.com </a>
        <a href="#">
          <i class="fas fa-map"></i> Kragujevac, Serbia - 34000
        </a>
      </div>
      <div class="box">
        <h3>follow us</h3>
        <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
        <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
        <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
        <a href="#"> <i class="fab fa-linkedin"></i> linkedin </a>
      </div>
    </div>
    <div class="credit">
      created by <span>Tripify team</span> | all rights reserved!
    </div>
  </section>
{% endblock content %}

backend/tripify/templates/reservations.html
{% extends "__base.html" %}
{% load static %}
{% block content %}
  <div class="heading"
       style="background: url({% static 'images/header-bg-1.png' %}) no-repeat">
    <h1>reservations</h1>
  </div>
  <div class="reservations">
  {% for reservation in reservations %}
  <div class="reservation">
  <p>
  {{ reservation.aranzman.naziv }}
  </p>
  <p>
    {{ reservation.broj_odraslih }} adults
  </p>
  <p>
    {{ reservation.broj_dece }} children
  </p>
  <p>
    Payment method: {{ reservation.get_nacin_placanja_display }}
  </p>
  Comment:
  <p>
    {{ reservation.komentar|linebreaksbr }}
  </p>
  <a href="/reservations/?cancel=&id={{ reservation.id }}" class='red'>
    Cancel
  </a>
</div>
  {% endfor %}
</div>
  <!-- about section starts  -->
{% endblock content %}